In [1]:
import math
import numpy

In [2]:
%run Gibbs_MTM.py

In [3]:
X = Gibbs_sampler(10, 10, 5, .2, N = 100)
X

array([[2., 2., 2., 0., 1., 3., 2., 1., 2., 1.],
       [3., 0., 2., 1., 2., 2., 2., 1., 2., 1.],
       [2., 0., 2., 3., 1., 0., 0., 0., 0., 1.],
       [2., 2., 2., 2., 2., 0., 1., 1., 0., 1.],
       [3., 2., 2., 3., 3., 2., 2., 1., 0., 2.],
       [3., 4., 2., 2., 2., 2., 3., 2., 2., 1.],
       [2., 3., 4., 1., 1., 2., 2., 2., 0., 1.],
       [2., 2., 3., 1., 1., 2., 3., 2., 1., 0.],
       [3., 2., 4., 2., 2., 2., 2., 1., 2., 1.],
       [2., 2., 2., 2., 1., 1., 2., 1., 0., 1.]])

In [4]:
np.shape(X)

(10, 10)

In [18]:
k1 = 3
k2 = 2
p = k1*k2
K = 5
beta = .2
n_reps = 100
m = 1
t = 1
gibbs_reps = 100

In [40]:
%%time
np.random.seed(100)
bigmatrix = sim(k1,k2,K,beta,10000,m,2,gibbs_reps)

Wall time: 2min 27s


In [8]:
np.shape(bigmatrix)

(10000, 12)

In [49]:
cormat = np.corrcoef(np.transpose(bigmatrix))
covmat = np.cov(np.transpose(bigmatrix))

In [10]:
np.shape(cormat)

(12, 12)

In [47]:
cormat[0:p,0:p]

array([[1.        , 0.51699696, 0.50587331, 0.38417041, 0.28660864,
        0.25028447],
       [0.51699696, 1.        , 0.39255786, 0.51671963, 0.24556092,
        0.26918152],
       [0.50587331, 0.39255786, 1.        , 0.53830265, 0.51243544,
        0.38039658],
       [0.38417041, 0.51671963, 0.53830265, 1.        , 0.3913961 ,
        0.50158966],
       [0.28660864, 0.24556092, 0.51243544, 0.3913961 , 1.        ,
        0.52412613],
       [0.25028447, 0.26918152, 0.38039658, 0.50158966, 0.52412613,
        1.        ]])

In [48]:
cormat[p:12,p:12]

array([[1.        , 0.51699554, 0.50246149, 0.39053246, 0.26888397,
        0.23423208],
       [0.51699554, 1.        , 0.38471286, 0.50497946, 0.24558588,
        0.2738305 ],
       [0.50246149, 0.38471286, 1.        , 0.53368398, 0.5053737 ,
        0.37081743],
       [0.39053246, 0.50497946, 0.53368398, 1.        , 0.39045302,
        0.49864822],
       [0.26888397, 0.24558588, 0.5053737 , 0.39045302, 1.        ,
        0.5164359 ],
       [0.23423208, 0.2738305 , 0.37081743, 0.49864822, 0.5164359 ,
        1.        ]])

In [51]:
[np.max(np.abs((cormat[0:p,0:p] - cormat[p:,p:]))),np.max(np.abs((covmat[0:p,0:p] - covmat[p:,p:])))]

[0.017724672544801867, 0.029591139113911535]

In [52]:
a = cormat[0:p,0:p] - cormat[0:p,p:]
a = a - np.diag(np.diag(a))
b = covmat[0:p,0:p] - covmat[0:p,p:]
b = b - np.diag(np.diag(b))
[np.max(np.abs(a)),np.max(np.abs(b))]

[0.016912775509686173, 0.02487700770077056]

In [19]:
bigarray = np.zeros([k1,k2,2,n_reps])
bigmatrix = np.zeros([n_reps,2*k1*k2])

In [24]:
%%time
for i in range(n_reps):
    bigarray[:,:,0,i] = Gibbs_sampler(k1, k2, 5, beta, gibbs_reps)
    bigmatrix[i,0:(k1*k2)] = np.reshape(bigarray[:,:,0,i],k1*k2)

Wall time: 1.22 s


In [25]:
%%time
for i in range(n_reps):
    bigarray[:,:,1,i] = SCEP_MH_Gibbs(k1, k2, 5, beta, bigarray[:,:,0,i], 0.9, m, t) # I tried m=t=1
    bigmatrix[i,(k1*k2):(2*k1*k2)] = np.reshape(bigarray[:,:,1,i],k1*k2)

Wall time: 497 ms


In [30]:
%%time
for i in range(n_reps):
    bigarray[:,:,0,i] = Gibbs_sampler(k1, k2, 50, beta, gibbs_reps)
    bigmatrix[i,0:(k1*k2)] = np.reshape(bigarray[:,:,0,i],k1*k2)

Wall time: 16.9 s


In [31]:
%%time
for i in range(n_reps):
    bigarray[:,:,1,i] = SCEP_MH_Gibbs(k1, k2, 50, beta, bigarray[:,:,0,i], 0.9, m, t) # I tried m=t=1
    bigmatrix[i,(k1*k2):(2*k1*k2)] = np.reshape(bigarray[:,:,1,i],k1*k2)

Wall time: 772 ms


In [32]:
%%time
for i in range(n_reps):
    bigarray[:,:,0,i] = Gibbs_sampler(k1, k2, 100, beta, gibbs_reps)
    bigmatrix[i,0:(k1*k2)] = np.reshape(bigarray[:,:,0,i],k1*k2)

Wall time: 49 s


In [33]:
%%time
for i in range(n_reps):
    bigarray[:,:,1,i] = SCEP_MH_Gibbs(k1, k2, 100, beta, bigarray[:,:,0,i], 0.9, m, t) # I tried m=t=1
    bigmatrix[i,(k1*k2):(2*k1*k2)] = np.reshape(bigarray[:,:,1,i],k1*k2)

Wall time: 725 ms
