In [1]:
import math
import numpy

In [2]:
%run Gibbs_MTM.py

In [3]:
X = Gibbs_sampler(10, 10, 5, .2, N = 100)
X

array([[2., 2., 2., 0., 1., 3., 2., 1., 2., 1.],
       [3., 0., 2., 1., 2., 2., 2., 1., 2., 1.],
       [2., 0., 2., 3., 1., 0., 0., 0., 0., 1.],
       [2., 2., 2., 2., 2., 0., 1., 1., 0., 1.],
       [3., 2., 2., 3., 3., 2., 2., 1., 0., 2.],
       [3., 4., 2., 2., 2., 2., 3., 2., 2., 1.],
       [2., 3., 4., 1., 1., 2., 2., 2., 0., 1.],
       [2., 2., 3., 1., 1., 2., 3., 2., 1., 0.],
       [3., 2., 4., 2., 2., 2., 2., 1., 2., 1.],
       [2., 2., 2., 2., 1., 1., 2., 1., 0., 1.]])

In [4]:
np.shape(X)

(10, 10)

In [18]:
k1 = 3
k2 = 2
p = k1*k2
K = 5
beta = .2
n_reps = 100
m = 1
t = 1
gibbs_reps = 100

In [16]:
%%time
np.random.seed(100)
bigmatrix = sim(k1,k2,K,beta,100,m,t,gibbs_reps)

Wall time: 1.72 s


In [8]:
np.shape(bigmatrix)

(10000, 12)

In [9]:
cormat = np.corrcoef(np.transpose(bigmatrix))

In [10]:
np.shape(cormat)

(12, 12)

In [12]:
cormat[0:p,0:p]

array([[1.        , 0.51699696, 0.50587331, 0.38417041, 0.28660864,
        0.25028447],
       [0.51699696, 1.        , 0.39255786, 0.51671963, 0.24556092,
        0.26918152],
       [0.50587331, 0.39255786, 1.        , 0.53830265, 0.51243544,
        0.38039658],
       [0.38417041, 0.51671963, 0.53830265, 1.        , 0.3913961 ,
        0.50158966],
       [0.28660864, 0.24556092, 0.51243544, 0.3913961 , 1.        ,
        0.52412613],
       [0.25028447, 0.26918152, 0.38039658, 0.50158966, 0.52412613,
        1.        ]])

In [13]:
cormat[p:12,p:12]

array([[1.        , 0.53231939, 0.50779335, 0.41034004, 0.27894818,
        0.24862446],
       [0.53231939, 1.        , 0.38791619, 0.51935862, 0.23772705,
        0.27236524],
       [0.50779335, 0.38791619, 1.        , 0.53246545, 0.50154421,
        0.37611898],
       [0.41034004, 0.51935862, 0.53246545, 1.        , 0.38541165,
        0.50699096],
       [0.27894818, 0.23772705, 0.50154421, 0.38541165, 1.        ,
        0.52138122],
       [0.24862446, 0.27236524, 0.37611898, 0.50699096, 0.52138122,
        1.        ]])

In [14]:
np.max(np.abs((cormat[0:p,0:p] - cormat[p:,p:])))

0.026169626263717494

In [15]:
a = cormat[0:p,0:p] - cormat[0:p,p:]
a = a - np.diag(np.diag(a))
np.max(a)

0.011663640409504406

In [19]:
bigarray = np.zeros([k1,k2,2,n_reps])
bigmatrix = np.zeros([n_reps,2*k1*k2])

In [24]:
%%time
for i in range(n_reps):
    bigarray[:,:,0,i] = Gibbs_sampler(k1, k2, 5, beta, gibbs_reps)
    bigmatrix[i,0:(k1*k2)] = np.reshape(bigarray[:,:,0,i],k1*k2)

Wall time: 1.22 s


In [25]:
%%time
for i in range(n_reps):
    bigarray[:,:,1,i] = SCEP_MH_Gibbs(k1, k2, 5, beta, bigarray[:,:,0,i], 0.9, m, t) # I tried m=t=1
    bigmatrix[i,(k1*k2):(2*k1*k2)] = np.reshape(bigarray[:,:,1,i],k1*k2)

Wall time: 497 ms


In [30]:
%%time
for i in range(n_reps):
    bigarray[:,:,0,i] = Gibbs_sampler(k1, k2, 50, beta, gibbs_reps)
    bigmatrix[i,0:(k1*k2)] = np.reshape(bigarray[:,:,0,i],k1*k2)

Wall time: 16.9 s


In [31]:
%%time
for i in range(n_reps):
    bigarray[:,:,1,i] = SCEP_MH_Gibbs(k1, k2, 50, beta, bigarray[:,:,0,i], 0.9, m, t) # I tried m=t=1
    bigmatrix[i,(k1*k2):(2*k1*k2)] = np.reshape(bigarray[:,:,1,i],k1*k2)

Wall time: 772 ms


In [32]:
%%time
for i in range(n_reps):
    bigarray[:,:,0,i] = Gibbs_sampler(k1, k2, 100, beta, gibbs_reps)
    bigmatrix[i,0:(k1*k2)] = np.reshape(bigarray[:,:,0,i],k1*k2)

Wall time: 49 s


In [33]:
%%time
for i in range(n_reps):
    bigarray[:,:,1,i] = SCEP_MH_Gibbs(k1, k2, 100, beta, bigarray[:,:,0,i], 0.9, m, t) # I tried m=t=1
    bigmatrix[i,(k1*k2):(2*k1*k2)] = np.reshape(bigarray[:,:,1,i],k1*k2)

Wall time: 725 ms
