In [120]:
import math
import numpy

In [121]:
%run Gibbs_MTM.py

In [122]:
X = Gibbs_sampler(10, 10, 5, .2, N = 100)
X

array([[2., 1., 1., 1., 3., 2., 1., 2., 1., 1.],
       [2., 3., 4., 2., 3., 3., 3., 2., 2., 1.],
       [2., 2., 2., 2., 3., 2., 2., 3., 1., 1.],
       [3., 3., 2., 1., 3., 2., 1., 3., 4., 3.],
       [2., 2., 3., 2., 1., 1., 2., 3., 3., 2.],
       [1., 1., 2., 1., 2., 3., 3., 3., 3., 4.],
       [1., 1., 1., 1., 1., 1., 0., 2., 2., 0.],
       [1., 2., 3., 2., 1., 2., 2., 2., 1., 1.],
       [2., 2., 2., 1., 1., 2., 1., 1., 1., 0.],
       [2., 1., 2., 1., 1., 2., 2., 2., 1., 1.]])

In [123]:
np.shape(X)

(10, 10)

In [152]:
k1 = 3
k2 = 2
p = k1*k2
K = 5
beta = .2
n_reps = 1000
m = 1
t = 1
gibbs_reps = 100

In [153]:
%%time
np.random.seed(100)
bigmatrix = sim(k1,k2,K,beta,n_reps,m,t,gibbs_reps)

CPU times: user 14.3 s, sys: 119 ms, total: 14.4 s
Wall time: 14.7 s


In [154]:
np.shape(bigmatrix)

(500, 12)

In [155]:
cormat = np.corrcoef(np.transpose(bigmatrix))

In [156]:
np.shape(cormat)

(12, 12)

Check that $X$ and $\tilde X$ have the same covariance

In [157]:
cormat[0:3,0:3]

array([[1.        , 0.52830397, 0.56369231],
       [0.52830397, 1.        , 0.41336182],
       [0.56369231, 0.41336182, 1.        ]])

In [158]:
cormat[9:12,9:12]

array([[1.        , 0.44499027, 0.55108528],
       [0.44499027, 1.        , 0.5324113 ],
       [0.55108528, 0.5324113 , 1.        ]])

In [159]:
np.max(np.abs((cormat[0:p,0:p] - cormat[p:,p:])))

0.06928656410323347

Check that $X$ and $\tilde X$ have the right cross-covariance

In [160]:
a = cormat[0:p,0:p] - cormat[0:p,p:]
a = a - np.diag(np.diag(a))
np.max(a)

0.04764367338014852