In [120]:
import math
import numpy

In [121]:
%run Gibbs_MTM.py

In [122]:
X = Gibbs_sampler(10, 10, 5, .2, N = 100)
X

array([[2., 1., 1., 1., 3., 2., 1., 2., 1., 1.],
       [2., 3., 4., 2., 3., 3., 3., 2., 2., 1.],
       [2., 2., 2., 2., 3., 2., 2., 3., 1., 1.],
       [3., 3., 2., 1., 3., 2., 1., 3., 4., 3.],
       [2., 2., 3., 2., 1., 1., 2., 3., 3., 2.],
       [1., 1., 2., 1., 2., 3., 3., 3., 3., 4.],
       [1., 1., 1., 1., 1., 1., 0., 2., 2., 0.],
       [1., 2., 3., 2., 1., 2., 2., 2., 1., 1.],
       [2., 2., 2., 1., 1., 2., 1., 1., 1., 0.],
       [2., 1., 2., 1., 1., 2., 2., 2., 1., 1.]])

In [123]:
np.shape(X)

(10, 10)

In [143]:
k1 = 3
k2 = 2
p = k1*k2
K = 5
beta = .2
n_reps = 100
m = 1
t = 1
gibbs_reps = 100

In [144]:
%%time
np.random.seed(100)
bigmatrix = sim(k1,k2,K,beta,n_reps,m,t,gibbs_reps)

CPU times: user 2.51 s, sys: 15.1 ms, total: 2.53 s
Wall time: 2.53 s


In [145]:
np.shape(bigmatrix)

(100, 12)

In [146]:
cormat = np.corrcoef(np.transpose(bigmatrix))

In [147]:
np.shape(cormat)

(12, 12)

In [148]:
cormat[0:3,0:3]

array([[1.        , 0.60335831, 0.65597813],
       [0.60335831, 1.        , 0.49614029],
       [0.65597813, 0.49614029, 1.        ]])

In [149]:
cormat[9:12,9:12]

array([[1.        , 0.48739583, 0.54668008],
       [0.48739583, 1.        , 0.53931282],
       [0.54668008, 0.53931282, 1.        ]])

In [150]:
np.max(np.abs((cormat[0:p,0:p] - cormat[p:,p:])))

0.17293264910659223

In [151]:
a = cormat[0:p,0:p] - cormat[0:p,p:]
a = a - np.diag(np.diag(a))
np.max(a)

0.12589447212407318