In [215]:
import numpy as np
from cvxopt import matrix, solvers

In [209]:
p = 100
rhos = .6 * np.ones(p)

In [210]:
cormatrix = np.ones([p,p])
for i in range(p-1):
    for j in range(i+1,p):
        for k in range(i,j):
            cormatrix[i,j] = cormatrix[i,j]*rhos[k]
        cormatrix[j,i] = cormatrix[i,j]

In [211]:
p = np.shape(cormatrix)[1]
c = -np.ones(p)
Gs  = []
Gs = np.zeros((p, p*p))
for i in range(p):
    Gs[i, i*p + i] = 1.0

In [212]:
c = matrix(c)
Gs = [matrix(Gs.T)]
hs = [matrix(2 * cormatrix)]
G0 = matrix(-(np.identity(p)))
h0 = matrix(np.zeros(p))

sol = solvers.sdp(c, Gl=G0, hl=h0, Gs=Gs, hs=hs)

     pcost       dcost       gap    pres   dres   k/t
 0: -1.0000e+02 -4.0000e+02  7e+02  7e-01  2e-16  1e+00
 1: -6.4464e+01 -9.8955e+01  7e+01  8e-02  1e-15  3e-01
 2: -5.3250e+01 -6.2294e+01  1e+01  2e-02  1e-15  1e-01
 3: -5.1617e+01 -5.3047e+01  2e+00  4e-03  1e-15  2e-02
 4: -5.1299e+01 -5.2177e+01  1e+00  2e-03  1e-15  9e-03
 5: -5.0992e+01 -5.1104e+01  2e-01  3e-04  3e-15  1e-03
 6: -5.0956e+01 -5.0995e+01  6e-02  1e-04  2e-15  3e-04
 7: -5.0939e+01 -5.0942e+01  5e-03  8e-06  1e-15  3e-05
 8: -5.0938e+01 -5.0938e+01  7e-04  1e-06  2e-15  4e-06
 9: -5.0938e+01 -5.0938e+01  2e-05  4e-08  1e-15  1e-07
Optimal solution found.


In [213]:
sol

{'x': <100x1 matrix, tc='d'>,
 'y': <0x1 matrix, tc='d'>,
 'status': 'optimal',
 'gap': 2.350168154526887e-05,
 'relative gap': 4.613826368102318e-07,
 'primal objective': -50.937507548501856,
 'dual objective': -50.937523193812346,
 'primal infeasibility': 3.826758057013982e-08,
 'dual infeasibility': 1.0934518059414841e-15,
 'primal slack': 2.759080403958013e-09,
 'dual slack': 1.1272987005474419e-08,
 'residual as primal infeasibility certificate': None,
 'residual as dual infeasibility certificate': None,
 'iterations': 9,
 'sl': <100x1 matrix, tc='d'>,
 'ss': [<100x100 matrix, tc='d'>],
 'zl': <100x1 matrix, tc='d'>,
 'zs': [<100x100 matrix, tc='d'>]}

In [202]:
x

array([[1.24992368],
       [0.05011249],
       [0.76994833],
       [0.33801763],
       [0.5972084 ],
       [0.44166751],
       [0.53500589],
       [0.47899329],
       [0.51259954],
       [0.49244294],
       [0.50453033],
       [0.49728343],
       [0.50162837],
       [0.49902264],
       [0.5005866 ],
       [0.4996472 ],
       [0.50021152],
       [0.499872  ],
       [0.50007625],
       [0.49995362],
       [0.50002742],
       [0.49998306],
       [0.50000964],
       [0.4999937 ],
       [0.50000338],
       [0.49999772],
       [0.50000123],
       [0.49999918],
       [0.50000044],
       [0.49999974],
       [0.50000023],
       [0.50000002],
       [0.50000022],
       [0.50000015],
       [0.50000024],
       [0.50000023],
       [0.50000029],
       [0.5000003 ],
       [0.50000033],
       [0.50000035],
       [0.50000037],
       [0.50000039],
       [0.5000004 ],
       [0.50000041],
       [0.50000043],
       [0.50000043],
       [0.50000044],
       [0.500

In [53]:
len(Gs[0])

10000

In [65]:
matrix(np.ones(5))

<5x1 matrix, tc='d'>

In [225]:
def ar_cov_matrix(rhos):
    p = np.shape(rhos)[0] + 1
    cormatrix = np.ones([p,p])
    for i in range(p-1):
        for j in range(i+1,p):
            for k in range(i,j):
              cormatrix[i,j] = cormatrix[i,j]*rhos[k]
            cormatrix[j,i] = cormatrix[i,j]

    return cormatrix

# solves the SDP
def sdp_solver(cormatrix):
    p = np.shape(cormatrix)[0]
    c = -np.ones(p)
    Gs  = []
    Gs = np.zeros((p, p*p))
    for i in range(p):
        Gs[i, i*p + i] = 1.0

    c = matrix(c)
    Gs = [matrix(Gs.T)]
    hs = [matrix(2 * cormatrix)]
    G0 = -matrix(-(np.identity(p)))
    h0 = matrix(np.zeros(p))

    sol = solvers.sdp(c, Gl=G0, hl=h0, Gs=Gs, hs=hs)
    return np.array(sol['x'])

In [229]:
S = ar_cov_matrix(np.array([.8,.4]))

In [230]:
S

array([[1.  , 0.8 , 0.32],
       [0.8 , 1.  , 0.4 ],
       [0.32, 0.4 , 1.  ]])

In [231]:
sdp_solver(S)

     pcost       dcost       gap    pres   dres   k/t
 0: -3.0000e+00 -3.0000e+00  6e+00  1e+00  2e-16  1e+00
 1: -5.4764e-01 -5.4764e-01  6e-01  1e-01  5e-16  1e-01
 2: -1.0992e-02 -1.0992e-02  2e-02  4e-03  1e-16  3e-03
 3: -1.1013e-04 -1.1013e-04  2e-04  4e-05  2e-16  3e-05
 4: -1.1013e-06 -1.1013e-06  2e-06  4e-07  4e-16  3e-07
 5: -1.1013e-08 -1.1013e-08  2e-08  4e-09  3e-16  3e-09
Optimal solution found.


array([[3.23628196e-09],
       [2.77366296e-09],
       [5.00309378e-09]])